### ISSUE TITLE
Extend support for other Facebook URLs

### ISSUE THREAD

**Issue by FabianOvrWrt** [elninosi/FXOS-FB-MenuTop-Add-on#2]
I've noticed that some carriers redirect the site m.facebook.com to others like lm.facebook.com and mobile.facebook.com with data enabled (I don't know why or if it only happens in my country), so when you open Facebook the Add-on doesn't work.

**Comment by elninosi** [comment]
Added lm, mobile and touch support (3f0ad21).

**Comment by elninosi** [comment]
Add-on was updated and approved on Firefox Marketplace: https://marketplace.firefox.com/addon/facebook-top-menu/
